import { supabase } from '@/lib/supabase';
import type { RecommendInput } from '../types/certifications.types';

class CertificationsService {
  /**
   * Get all issued/revoked certificates for a student.
   */
  async getCertificationsForStudent(studentId: string) {
    return supabase
      .from('certifications')
      .select(
        '*, program:programs(name, name_ar), track:program_tracks(name, name_ar), teacher:profiles!certifications_teacher_id_fkey(full_name, display_name)',
      )
      .eq('student_id', studentId)
      .in('status', ['issued', 'revoked'])
      .order('issue_date', { ascending: false });
  }

  /**
   * Get a single certification by ID with full joined details.
   */
  async getCertificationById(certificationId: string) {
    return supabase
      .from('certifications')
      .select(
        '*, program:programs(name, name_ar), track:program_tracks(name, name_ar), teacher:profiles!certifications_teacher_id_fkey(full_name, display_name), issuer:profiles!certifications_issued_by_fkey(full_name, display_name)',
      )
      .eq('id', certificationId)
      .single();
  }

  /**
   * Get certification requests for a program, optionally filtered by status.
   */
  async getCertificationRequests(programId: string, status?: string) {
    let query = supabase
      .from('certifications')
      .select(
        '*, student:profiles!certifications_student_id_fkey(full_name, display_name, avatar_url), teacher:profiles!certifications_teacher_id_fkey(full_name)',
      )
      .eq('program_id', programId)
      .order('created_at', { ascending: false });

    if (status) {
      query = query.eq('status', status);
    }

    return query;
  }

  /**
   * Teacher recommends a student for certification.
   * Calls get_certification_eligibility RPC to validate first.
   */
  async recommendForCertification(input: RecommendInput) {
    return supabase.from('certifications').insert({
      student_id: input.student_id,
      program_id: input.program_id,
      track_id: input.track_id,
      enrollment_id: input.enrollment_id,
      type: input.type,
      title: input.title,
      title_ar: input.title_ar,
      teacher_id: input.teacher_id,
      recommended_by: input.teacher_id,
      status: 'recommended',
    }).select().single();
  }

  /**
   * Supervisor approves or rejects a certification request.
   */
  async reviewCertification(
    certificationId: string,
    action: 'approve' | 'reject',
    supervisorId: string,
    note?: string,
  ) {
    if (action === 'approve') {
      return supabase
        .from('certifications')
        .update({ status: 'supervisor_approved', supervisor_id: supervisorId })
        .eq('id', certificationId)
        .select()
        .single();
    }

    return supabase
      .from('certifications')
      .update({ status: 'rejected', rejection_reason: note, supervisor_id: supervisorId })
      .eq('id', certificationId)
      .select()
      .single();
  }

  /**
   * Program admin issues a certification. Certificate number is auto-generated by trigger.
   */
  async issueCertification(
    certificationId: string,
    issuedBy: string,
    chainOfNarration?: string,
  ) {
    return supabase
      .from('certifications')
      .update({
        status: 'issued',
        issued_by: issuedBy,
        issue_date: new Date().toISOString(),
        chain_of_narration: chainOfNarration ?? null,
      })
      .eq('id', certificationId)
      .select()
      .single();
  }

  /**
   * Revoke an issued certificate with a mandatory reason.
   */
  async revokeCertification(
    certificationId: string,
    revokedBy: string,
    reason: string,
  ) {
    return supabase
      .from('certifications')
      .update({
        status: 'revoked',
        revoked_by: revokedBy,
        revocation_reason: reason,
      })
      .eq('id', certificationId)
      .select()
      .single();
  }

  /**
   * Check if a student is eligible for certification via RPC.
   */
  async checkCertificationEligibility(enrollmentId: string) {
    return supabase.rpc('get_certification_eligibility', {
      p_enrollment_id: enrollmentId,
    });
  }
}

export const certificationsService = new CertificationsService();
